# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

juliacall_initialize <- function(libpath, julia_bindir, image_relative_path) {
    .Call('_JuliaCall_juliacall_initialize', PACKAGE = 'JuliaCall', libpath, julia_bindir, image_relative_path)
}

juliacall_cmd <- function(libpath) {
    .Call('_JuliaCall_juliacall_cmd', PACKAGE = 'JuliaCall', libpath)
}

juliacall_docall <- function(jcall) {
    .Call('_JuliaCall_juliacall_docall', PACKAGE = 'JuliaCall', jcall)
}

juliacall_atexit_hook <- function(status) {
    invisible(.Call('_JuliaCall_juliacall_atexit_hook', PACKAGE = 'JuliaCall', status))
}

