# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

juliacall_initialize <- function(libpath) {
    .Call('_JuliaCall_juliacall_initialize', PACKAGE = 'JuliaCall', libpath)
}

juliacall_cmd <- function(libpath) {
    .Call('_JuliaCall_juliacall_cmd', PACKAGE = 'JuliaCall', libpath)
}

juliacall_docall <- function(jcall) {
    .Call('_JuliaCall_juliacall_docall', PACKAGE = 'JuliaCall', jcall)
}

